[feat][clock] Add digital clock output command
yannbertrand/macos-defaults pull request #56
Opened 2020-10-04 16:33 UTC by jidicula

**Why this change was necessary**
The command for setting menubar digital clock output was missing from
the list.

**What this change does**
Adds config information for the digital clock time and date format
with a few examples.

**Any side-effects?**
None.

Note that I haven't tested this on Big Sur. Once this testing is complete, I can add Big Sur in the `versions` field.

**Additional context/notes/links**

Resolves yannbertrand/macos-defaults#41

See also: https://github.com/herrbischoff/awesome-macos-command-line#set-menu-bar-clock-output-format

2020-10-04 16:49 UTC, jidicula commented
Did I do something wrong with the filename for the video recording? The [deploy check](https://app.netlify.com/sites/macos-defaults/deploys/5f79fbb023e6f9000902a306) failed with this message:

```
12:45:42 PM: Error: ENOENT: no such file or directory, copyfile '../../images/menubar/DateFormat/EEE d MMM HH:mm:ss.mp4' -> 'docs//menubar/menubar-DateFormat-EEE d MMM HH:mm:ss.mp4'
```

2020-10-04 16:55 UTC, yannbertrand commented
That means the video files don't exist 😄

If you want to generate them, you'll have to create [a script to do it programmatically](https://github.com/yannbertrand/macos-defaults/tree/master/record#readme). You can take a look at the [menubar FlashDateSeparators](https://github.com/yannbertrand/macos-defaults/blob/master/record/menubar/FlashDateSeparators/true.js) scripts that should be very similar.

If you don't want to do it, I'll add it for you 😉

2020-10-04 17:02 UTC, jidicula commented
> That means the video files don't exist 😄
> 
> If you want to generate them, you'll have to create [a script to do it programmatically](https://github.com/yannbertrand/macos-defaults/tree/master/record#readme). You can take a look at the [menubar FlashDateSeparators](https://github.com/yannbertrand/macos-defaults/blob/master/record/menubar/FlashDateSeparators/true.js) scripts that should be very similar.
> 
> If you don't want to do it, I'll add it for you 😉

Sure, I can take a crack at it 🙂. Quick question though, when I name the js script, it makes sense to name it after the config's value that has been applied – if I follow this convention, how should I handle the spaces in the filename? Any pitfalls I should be aware of, or is it "safe" to just name the script `EEE d MMM HH:mm:ss.js` for example.

2020-10-04 17:06 UTC, yannbertrand commented
> > That means the video files don't exist 😄
> > If you want to generate them, you'll have to create [a script to do it programmatically](https://github.com/yannbertrand/macos-defaults/tree/master/record#readme). You can take a look at the [menubar FlashDateSeparators](https://github.com/yannbertrand/macos-defaults/blob/master/record/menubar/FlashDateSeparators/true.js) scripts that should be very similar.
> > If you don't want to do it, I'll add it for you 😉
> 
> Sure, I can take a crack at it 🙂. Quick question though, when I name the js script, it makes sense to name it after the config's value that has been applied – if I follow this convention, how should I handle the spaces in the filename? Any pitfalls I should be aware of, or is it "safe" to just name the script `EEE d MMM HH:mm:ss.js` for example.

Cool. I'd say use underscores `_` instead of spaces ` ` in the file name.

2020-10-04 18:20 UTC, jidicula commented
Ok, I *thought* I set up the recording scripts correctly but the Netlify build still failed 😦 – where am I going wrong?

2020-10-04 18:40 UTC, yannbertrand commented
You did good! Afaik, Netlify or other servers can't run these scripts themselves. In fact I run them on my Mac and upload the videos inside the repo.

So let me run them locally and I'll push them afterwards!

2020-10-04 19:10 UTC, yannbertrand requested changes
Just a few notes.

Will probably add some examples later, and I need to fix something on the code snippets before merging.

Thanks again!

2020-10-04 19:10 UTC, yannbertrand commented on defaults.yml
> +          week, `d MMM` for day of the month and 3-letter month.
```suggestion
          This setting configures the time and date format for the menubar
          digital clock. Default value depends on your locale settings. `ss`
          for seconds, `HH` for 24-hour clock, `EEE` for 3-letter day of the
          week, `d MMM` for day of the month and 3-letter month.
          These commands could have a different result depending on the Language & Region parameters.
```

2020-10-04 19:10 UTC, yannbertrand commented on defaults.yml
> +        versions: [Catalina]
```suggestion
        versions: [Big Sur, Catalina]
```

2020-10-04 19:10 UTC, yannbertrand commented on defaults.yml
> +        after: killall SystemUIServer
killall SystemUIServer is not required
```suggestion
```

2020-10-04 19:10 UTC, yannbertrand commented on defaults.yml
> +            text: "Example time output: Thu 18 Aug 21:46:18"
```suggestion
            text: Thu 18 Aug 21:46:18
```

2020-10-04 19:10 UTC, yannbertrand commented on defaults.yml
> +            text: "Example time output: Thu 9:46:18"
```suggestion
            text: Thu 9:46:18
```

2020-10-04 19:10 UTC, yannbertrand commented on defaults.yml
> +            text: "Example time output: Thu 21:46:18"
```suggestion
            text: Thu 21:46:18
```

2020-10-04 19:13 UTC, yannbertrand commented
Here are the video files, if you can push them on your branch! 😄 

[DateFormat.zip](https://github.com/yannbertrand/macos-defaults/files/5324144/DateFormat.zip)

2020-10-04 20:20 UTC, jidicula commented
> Here are the video files, if you can push them on your branch! 😄
> 
> [DateFormat.zip](https://github.com/yannbertrand/macos-defaults/files/5324144/DateFormat.zip)

Did the filenames get changed? I see slashes instead of colons.

2020-10-04 20:22 UTC, yannbertrand commented
> > Here are the video files, if you can push them on your branch! 😄
> > [DateFormat.zip](https://github.com/yannbertrand/macos-defaults/files/5324144/DateFormat.zip)
> 
> Did the filenames get changed? I see slashes instead of colons.

I'm not sure why it does that, it should be colons.

2020-10-04 20:23 UTC, jidicula commented
Looks like macOS doesn't like colons in filenames. I'll use dots instead.
![image](https://user-images.githubusercontent.com/12765385/95026222-df1ee080-065d-11eb-92c3-07e27891845d.png)

2020-10-04 20:26 UTC, yannbertrand requested changes
Fix website snippet copy/paste

2020-10-04 20:26 UTC, yannbertrand commented on defaults.yml
> +          - value: "EEE d MMM HH:mm:ss"
Fix snippet copy/paste
```suggestion
          - value: '"EEE d MMM HH:mm:ss"'
```

2020-10-04 20:26 UTC, yannbertrand commented on defaults.yml
> +          - value: "EEE h:mm:ss"
```suggestion
          - value: '"EEE h:mm:ss"'
```

2020-10-04 20:26 UTC, yannbertrand commented on defaults.yml
> +          - value: "EEE HH:mm:ss"
```suggestion
          - value: '"EEE HH:mm:ss"'
```

2020-10-04 22:21 UTC, jidicula commented
Looks like some issues with asset size:
![image](https://user-images.githubusercontent.com/12765385/95028447-52305300-066e-11eb-923a-5d819bdaa3ac.png)

Deploy looks fine otherwise though 😁

2020-10-05 05:55 UTC, yannbertrand commented
> Looks like some issues with asset size:
> ![image](https://user-images.githubusercontent.com/12765385/95028447-52305300-066e-11eb-923a-5d819bdaa3ac.png)
> 
> Deploy looks fine otherwise though 😁

😂 You got them all. That Lighthouse performance measure is unstable, it doesn't even run on the page you've created. Relaunching the build fixed it 😉

2020-10-05 05:55 UTC, yannbertrand approved these changes

2020-10-05 05:57 UTC, merged

2020-10-05 05:57 UTC, yannbertrand commented
Thank you so much again!