Add Dock Tilesize
yannbertrand/macos-defaults pull request #85
Opened 2020-10-27 17:25 UTC by moritzsternemann

This PR adds the `tilesize` key to the Dock section. It can be used to configure the size of the dock icons.

2020-10-27 17:43 UTC, moritzsternemann commented
@yannbertrand it would be awesome if you could run the new record scripts as I don't have the setup with another user ready.

2020-10-31 14:07 UTC, yannbertrand requested changes
Looks almost perfect! Thanks for the addition 😄 

Here are the generated screenshots:
![36](https://user-images.githubusercontent.com/5855339/97781284-8e31d780-1b8a-11eb-97a0-7c4f41b23e21.png)
![48](https://user-images.githubusercontent.com/5855339/97781285-8f630480-1b8a-11eb-9d8c-9c469213ae02.png)

2020-10-31 14:07 UTC, yannbertrand commented on record/dock/tilesize/36.js
> +    const { stderr: setEnvError } = await exec('defaults write com.apple.screencapture show-thumbnail -bool false && defaults write com.apple.dock tilesize -string bottom && killall Dock')
```suggestion
    const { stderr: setEnvError } = await exec('defaults write com.apple.screencapture show-thumbnail -bool false && defaults write com.apple.dock tilesize -int 36 && killall Dock')
```

2020-10-31 14:07 UTC, yannbertrand commented on record/dock/tilesize/48.js
> +    const { stderr: setEnvError } = await exec('defaults write com.apple.screencapture show-thumbnail -bool false && defaults write com.apple.dock tilesize -string bottom && killall Dock')
```suggestion
    const { stderr: setEnvError } = await exec('defaults write com.apple.screencapture show-thumbnail -bool false && defaults write com.apple.dock tilesize -int 48 && killall Dock')
```

2020-10-31 14:07 UTC, yannbertrand commented on defaults.yml
> +        versions: [Catalina]
```suggestion
        versions: [Big Sur, Catalina]
```

2020-10-31 14:07 UTC, yannbertrand commented
Quality should be a little better in a zip : [dock-tilesize.zip](https://github.com/yannbertrand/macos-defaults/files/5469204/dock-tilesize.zip)

2020-11-01 21:59 UTC, yannbertrand approved these changes

2020-11-01 21:59 UTC, yannbertrand commented
Thank you 🙂

2020-11-01 22:00 UTC, merged