Add command to disable application quarantine msg
yannbertrand/macos-defaults pull request #94
Opened 2020-11-16 00:52 UTC by issmirnov

Source: https://ss64.com/osx/syntax-defaults.html

2020-11-17 12:53 UTC, yannbertrand requested changes
I tried it on Big Sur, I'm not sure how to get this message?

Here is my settings:
<img width="780" alt="settings" src="https://user-images.githubusercontent.com/5855339/99391862-15957f80-28db-11eb-989a-2528779bf5ce.png">

That's what happens when trying to open a newly downloaded App using Spotlight:
<img width="372" alt="open-spotlight" src="https://user-images.githubusercontent.com/5855339/99391882-1e865100-28db-11eb-8f7a-688a90acc579.png">

And by right clicking it + "Open" in the Applications folder:
<img width="372" alt="open-applications-folder" src="https://user-images.githubusercontent.com/5855339/99391929-34941180-28db-11eb-93fd-3f648159c769.png">

Does it only affect downloaded Apps? Not the ones installed through Homebrew?

2020-11-17 12:53 UTC, yannbertrand commented on defaults.yml
> +            text: "Application Downloaded from Internet" popup will display
```suggestion
            text: '"Application Downloaded from Internet" popup will display'
```

2020-11-17 12:53 UTC, yannbertrand commented on defaults.yml
> +            text: "Application Downloaded from Internet" popup will not display
```suggestion
            text: '"Application Downloaded from Internet" popup will not display'
```

2020-11-17 12:55 UTC, yannbertrand approved these changes

2020-11-17 12:56 UTC, yannbertrand commented
Ok I think I found it by downloading a `.dmg` file and dragging the App to the Applications folder

2020-11-17 12:57 UTC, yannbertrand commented
<img width="372" alt="downloaded" src="https://user-images.githubusercontent.com/5855339/99392927-d10ae380-28dc-11eb-8716-a95fabd78b96.png">

2020-11-17 12:58 UTC, yannbertrand commented
```
defaults write com.apple.LaunchServices LSQuarantine -bool false
```

seems not to affect it tho

2020-11-28 23:58 UTC, issmirnov commented
You are right - I was testing on an older machine. Sorry about the confusion. Closing PR so that it doesn't clutter up the list.

2020-11-29 07:44 UTC, yannbertrand commented
It's alright! Will just had a warning to explain it doesn't work on Big Sur.

2020-11-29 07:47 UTC, yannbertrand commented on defaults.yml
> +        description: Turn off the “Application Downloaded from Internet” quarantine warning
```suggestion
        description:
          "Turn off the “Application Downloaded from Internet” quarantine warning.<br>
          :warning: Stopped working on Big Sur."
```

2020-11-29 07:52 UTC, yannbertrand commented on defaults.yml
> +          :warning: Stopped working on Big Sur."
```suggestion
          ⚠️ Stopped working on Big Sur."
```

2020-11-29 07:54 UTC, merged

2020-11-29 07:54 UTC, yannbertrand commented
Thank you 😄